#
# The development cloud build - that deploys the image to Cloud Run for testing
#
# _IMAGE_NAME: This is a GCP resource and no underscores are allowed
# [a-z]([-a-z0-9]*[a-z0-9])? is the regex for the resource name
#
# [START cloudbuild_gen_yaml]
steps:
  # [START cloudbuild_python_dependencies_yaml]
  # install dependecies
  # - name: python
  #   entrypoint: pip
  #   args: ["install", "-r", "requirements.txt", "--user"]
  # [END cloudbuild_python_dependencies_yaml]

  # - name: python
  #   entrypoint: python3
  #   args: ["-m", "unittest"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest || exit 0']

  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t',           'gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}',
           '-t',           'gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest',
           '--cache-from', 'gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest',
           '-f', '${_ROOTDIR}/Dockerfile',
           '${_ROOTDIR}']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}']
  # [END cloudbuild_python_push_yaml]
  
  # [START cloudbuild_python_deploy_yaml]
  # Deploy to Cloud Run
  - name: 'google/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args: ['run', 'services', 'update', '${_IMAGE_NAME}',
           '--image=gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}', 
           '--region', '$_DEPLOY_REGION', '--platform', 'managed']
  # [END cloudbuild_python_deploy_yaml]
  
# [START cloudbuild_python_logs_yaml]
# Save test logs to Google Cloud Storage
# artifacts:
#   objects:
#     location: gs://${_BUCKET_NAME}/
#     paths:
#       - ${SHORT_SHA}_test_log.xml
# [END cloudbuild_python_logs_yaml]

# Without this, build does not proceed
options:
  logging: CLOUD_LOGGING_ONLY
  
# Store images in Google Artifact Registry 
images:
  - gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}
  - gcr.io/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest
# [END cloudbuild_gen_yaml]